on: push
  branches: main
name: Deploy Over FTP
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: FTP Deploy
              uses: SamKirkland/FTP-Deploy-Action@master
              with:
                  server: ftp.jaredwebber.dev
                  username: gha@jaredwebber.dev
                  password: ${{ secrets.GHA_FTP_SECRET }}
                  dry-run: true
