on:
  push:
    branches:
      - main
name: Deploy Over FTP
id: deploy_over_ftp
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: FTP Deploy
        uses: Wandalen/wretry.action@master
        with:
          action: SamKirkland/FTP-Deploy-Action@master
          with: |
            server: ${{ secrets.GHA_FTP_DOMAIN }}
            username: github-actions@jaredwebber.dev
            password: ${{ secrets.GHA_FTP_SECRET }}
            local-dir: ./src/
          attempt_limit: 10
          attempt_delay: 5000
