on:
  push:
    branches:
      - main
# schedule:
#   - cron: 0 0 * * 0
name: Validate Site
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python ../tests/validation_pass.py -v
