on:
  schedule: [cron: "0 0 * * 0"]
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["Deploy Over FTP"]
    types:
      - completed

name: Validate Site
jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Restore Cache
        id: restore-cache
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}
          restore-keys: ${{ runner.os }}
      - name: Install Dependencies
        run: pip install selenium webdriver-manager
      - name: Run Tests
        run: python tests/validation_pass.py -v
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
